Task1
radudoros/cubrid pull request #1
Opened 2018-05-09 11:46 UTC by radudoros

- added palindrome function on strings & multiset of strings

2018-05-09 12:14 UTC, lucianlazar2211 requested changes
Please check the code-style and indent as follows:

```
if (statement)
<tab>{
<tab><tab> ...
<tab>}
```

Something like:
```
if (a == b)
  {
    a = a + 1;
  }
```

And similar for `while`, `for` etc..

2018-05-09 13:26 UTC, lucianlazar2211 requested changes

2018-05-09 13:26 UTC, lucianlazar2211 commented on src/optimizer/query_graph.c
> +  case PT_PALINDROME:
Please align the case with the others.

2018-05-09 13:26 UTC, lucianlazar2211 commented on src/parser/csql_lexer.l
> +[pP][aA][lL][iI][nN][dD][rR][oO][mM][eE]				{ begin_token(yytext); csql_yylval.cptr = pt_makename(yytext);
We have a 120 character line limit, please set `csql_yylval.cptr = pt_makename(yytext);` on the next line.

2018-05-09 13:26 UTC, lucianlazar2211 commented on src/parser/xasl_generation.c
> +					 || node->info.expr.op == PT_PALINDROME
Align with the others :)

2018-05-09 13:26 UTC, lucianlazar2211 commented on src/query/fetch.c
> +      break;
Fix indent for `if` structure.

2018-05-09 14:27 UTC, lucianlazar2211 approved these changes

2018-05-09 14:30 UTC, lucianlazar2211 commented
@ribram I feel like this is mature. :)

2018-05-10 11:09 UTC, ribram commented on src/query/string_opfunc.c
> +db_string_palindrome (const DB_VALUE *src_str, DB_VALUE *result_str)
Since it is not just for string, I think it is better to rename as db_palindrome to avoid confusion. Also argument src_str should be renamed (as value or eval_value or another name).

2018-05-10 11:09 UTC, ribram commented on src/query/string_opfunc.c
> +  DB_TYPE str_type = DB_VALUE_DOMAIN_TYPE(src_str);
Rename str_type as db_type or just type. Leave a space between macro/function name and parameter list (it is repeated in several places). It is best to run automatic indentation on file.

2018-05-10 11:09 UTC, ribram commented on src/query/string_opfunc.c
> +  assert(src_str != (DB_VALUE *)NULL);
Casting NULL to typed pointer is unnecessary.

2018-05-10 11:09 UTC, ribram commented on src/query/string_opfunc.c
> +  if (DB_IS_NULL(src_str))
Sometimes, especially when dealing with large blocks of code, it is better to do something like this:

```c
if (early_out_cond)
  {
     // do stuff
    return ...;
  } 
// else do stuff
```
instead of:
```c
if (early_out_cond)
  {
    // do stuff
  }
else
  {
    // else do stuff
  }
```

It is just a coding preference we learned in time, it is not mentioned in the coding style.

Your code would be:
```c
  if (DB_IS_NULL (src_str))
    {
      db_make_null (result_str);
      return NO_ERROR;
    }

  if (!QSTR_IS_ANY_CHAR(str_type) && str_type != DB_TYPE_MULTISET)
    {
      er_set (ER_ERROR_SEVERITY, ARG_FILE_LINE, ER_QSTR_INVALID_DATA_TYPE, 0);  // must also set error
      return ER_QSTR_INVALID_DATA_TYPE;
    }

  // the rest of code

2018-05-10 11:09 UTC, ribram commented on src/query/string_opfunc.c
> +	  unsigned char *str = (unsigned char *)db_get_string (src_str);
This seems an unnecessary change of type. str may be ```char *``` instead of ```unsigned char *```

2018-05-10 11:09 UTC, ribram commented on src/query/string_opfunc.c
> +	  for (int i = 0; i < len / 2 - 1; ++i)
Why stop before ```len / 2 - 1```? What happens when string is "ab"?

2018-05-10 11:09 UTC, ribram commented on src/query/string_opfunc.c
> +	      /* Compare each elem in multiset with first one (they have to be equal given the sets' ordering property)*/
Is multiset ordered? I did not know that :))

2018-05-10 11:09 UTC, ribram commented on src/query/string_opfunc.c
> +		  if (strcmp ((const char *)first_str, (const char *)crt_str) != 0)
Change type of first_str, crt_str to ```char *```. Then conversions to ```const char *``` will be unnecessary..

2018-06-13 12:34 UTC, closed without merging